# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, null=True)),
                ('subject', models.CharField(max_length=64, null=True)),
                ('message', models.TextField()),
                ('from_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
