# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(default='(000)0000000', max_length=15)),
                ('reestr', models.CharField(default='000000000000', max_length=50)),
                ('summa_max', models.PositiveIntegerField(default=15000)),
                ('stavka_max', models.PositiveIntegerField(default=2)),
                ('srok_max', models.PositiveIntegerField(default=28)),
            ],
        ),
    ]
