# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_organization_feedback_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='feedback_email',
            field=models.EmailField(default='anton@anton.ru', max_length=254),
            preserve_default=False,
        ),
    ]
