# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20171128_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=models.SlugField(default='mkkneit', max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
