# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_auto_20171130_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doc',
            name='file_doc',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
