# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20171130_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stavka_max',
            field=models.FloatField(default=2),
        ),
    ]
