# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_auto_20171201_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='office',
            name='org_id',
        ),
        migrations.DeleteModel(
            name='Office',
        ),
    ]
