# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 10:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_auto_20171201_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doc',
            name='org_id',
        ),
        migrations.DeleteModel(
            name='Doc',
        ),
    ]
